DEBUG=
DEBUGLINK=
MODEL=x
OPTIMIZE=-o+space -o+time
FLAGS=-cpp -br -c -a1 -3
LIBRX=d:\zordos\libdos\cx

.cpp.obj :
        ztc -m$(MODEL) $(OPTIMIZE) $(DEBUG) $(FLAGS) $*.cpp

all: mascot.exe

clean:
     del *.obj
     del *.bak
     del *.map
     del mascot.exe

f-eval.obj:	f-eval.cpp
    ztc f-eval.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
fxeval.obj:	fxeval.cpp
    ztc fxeval.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
fqeval.obj:	fqeval.cpp
    ztc fqeval.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
_scale.obj:	_scale.cpp
    ztc _scale.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
dxbout.obj:	dxbout.cpp
    ztc dxbout.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
tom_aray.obj:	tom_aray.cpp
    ztc tom_aray.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
fzinit.obj:	fzinit.cpp
    ztc fzinit.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
mgsort.obj:	mgsort.cpp
    ztc mgsort.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
m_alcr.obj:	m_alcr.cpp
    ztc m_alcr.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
fractf.obj:	fractf.cpp
    ztc fractf.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
f2size.obj:	f2size.cpp
    ztc f2size.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
f3size.obj:	f3size.cpp
    ztc f3size.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
m2pdif.obj:	m2pdif.cpp
    ztc m2pdif.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)
f1area.obj:	f1area.cpp
    ztc f1area.cpp $(OPTIMIZE) $(DEBUG) $(FLAGS) -m$(MODEL)

mascot.exe:  f-eval.obj tom_aray.obj fqeval.obj fxeval.obj dxbout.obj _scale.obj fzinit.obj mgsort.obj m_alcr.obj fractf.obj f2size.obj f3size.obj m2pdif.obj f1area.obj
	blinkr $(LIBRX)+f-eval+tom_aray+fqeval+fxeval+dxbout+_scale+fzinit+mgsort+m_alcr+fractf+f2size+f3size+m2pdif+f1area,mascot/noi

f-eval.obj:	f-eval.cpp
tom_aray.obj:	tom_aray.cpp
fqeval.obj:	fqeval.cpp
fxeval.obj:	fxeval.cpp
dxbout.obj:	dxbout.cpp
_scale.obj:	_scale.cpp
fzinit.obj:	fzinit.cpp
mgsort.obj:	mgsort.cpp
m_alcr.obj:	m_alcr.cpp
fractf.obj:	fractf.cpp
f2size.obj:	f2size.cpp
f3size.obj:	f3size.cpp
m2pdif.obj:	m2pdif.cpp
f1area.obj:	f1area.cpp

